name: 'Release: Publish To Docker Hub'
on:
  release:
    types: [published]

jobs:
  docker_hub:
    name: Publish to Docker Hub
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build docker image
        run: docker build ./ -t ${IMAGE_NAME} --file Dockerfile
      - name: Set version tag
        run: |
          TAG=`echo $GITHUB_REF | sed 's/refs\/tags\///g'`
          docker tag ${IMAGE_NAME} ${IMAGE_NAME}:${TAG}
      - name: Set latest tag
        if: github.event.release.prerelease == false
        run: docker tag ${IMAGE_NAME} ${IMAGE_NAME}:latest
      - name: Set pre-release tag
        if: github.event.release.prerelease == true
        run: docker tag ${IMAGE_NAME} ${IMAGE_NAME}:pre-release
      - name: Login to Docker Hub
        run: docker login --username slimehatena --password ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Publish version tag
        run: |
          TAG=`echo $GITHUB_REF | sed 's/refs\/tags\///g'`
          docker push ${IMAGE_NAME}:${TAG}
      - name: Publish latest tag
        if: github.event.release.prerelease == false
        run: docker push ${IMAGE_NAME}:latest
      - name: Publish pre-release tag
        if: github.event.release.prerelease == true
        run: docker push ${IMAGE_NAME}:pre-release
      - name: Slack Notification
        uses: 8398a7/action-slack@v2
        if: always()
        with:
          status: ${{ job.status }}
          author_name: ProjectPrimera/ongeki-score
          text: <!channel>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    env:
      IMAGE_NAME: projectprimera/ongeki-score
